sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: wmBdb02ZYi45BiI/BUua43EyjV25Jej3Wy+/Wca49biCa5POsT+1MCLUskpydXGexTUvyekZsWgsd9tIOv91SW3/Fd/GeXmF68so4TmWRX45BEO+OcPbOVFM/ww7G0rIcRqS8Idk6r/LLKJhewqrBCAyF95dO0HdAawrTDOId1hUM4S65bE2nkA0Am+IMtcUzIfpAaeM6rpf9RQEnIEItvXk/FbOoi+KYmzeKgxuPwPQ7mcl6LwPFID76GgwxcQIXOfguuJ6Iyy38SWvX4tCqsOsK7uBw6y46c0IQtoso2p//tRB9UdNP/k77sCWTy/P/G773TEvCAwGd+HU5nfr70XxIr7bWgVwCYwfvMbCRPoLsQqf38HNZOpHTO+uAbjseChogVU3ObofYOBAmP59YMkI4BFZSMiVcq0WDZTXN6Z57T2l66PdQPxQseCCKpKiGf4sTxE3laIj61RWYba1uC6wRlvTJjF9KBLS8KycTnK1+kziELwkFuNqewhsIXYaSntXfHUKG7noouv3hphbBs1fOPRPCS04WSXiWQBvClJqhfBmVDvmmLtXmm/udN5ZqC5/5xq+sO/GaFsKhtLS3lQQ99+b9j7rYEtuwb9PNm/PM1L2FtcyFYI9RXf69qwKNDAJFyjCgmi7nVES3+U911cGh6OUoG9utDG5lY4+XR4=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: DsUqF5wOtblZZ9uCPpu49QFBsbs+Xp8Gl8tJfqBX4ySjhsypr7hRFOT8sX26Wqx4hNJLO8u+We2itJX9KOf4nHubNoL57o5nLBM3wEWibUeFqG6an+u65V/t+Noc0055FEnOkCW2FRqVEuP5eBaQCzTZdW26VeAumOsAX/eQePQ1nIwey70pmz8+M6TqDS+IpRgXNmGZsaGgkkxZOmzhy0IfMtgmnL3Ono+DTXJa8vpvLL8YJC8rAJPbaLMKzYNiJ8AsyL1HHHGv3qOL8MtTfj0NiUkCZvuYPo4FuJ7ZTBmATcfbuuHG5bXdMz8abPtDCUQm9ydpIV80fLkgF8uN/1vJfAihtlhl4DQSeKTest66QSodYvDCRRvsVmNrQRp1bzMjZO6WjvuJSyVTJZRlxPC1jZ7GeTGCBieNzievJ95+cxIXMbZ0I/885rldA83YHbhQEiu/qwoTubkRNWjz7eC1CYZh8LRc2Qzu9n3psUzVHrwT/6aKQYDz0JRPzcLmn6HcXngN21LgtD7IU1/Z75uUOXDKpCCNL11g20O9I9h6pyI3sWKE7P42AiQEx+GDBKRyNmkQ9iG/JdjmdjexrgQyj77lacjLTFi77YTTpRtbOqxc6SjJ+UyLKP3SVOKOU7q1NUiJJ81APbeC+8vv5wnEvATi4kW2Wp/lywSYMG0=
